### ISSUE TITLE
Rework nights inputs

### ISSUE THREAD

**Issue by rakmo97** [TripSplit/TripSplit#2]
Currently the user specifies nights with numbers. We need to change it to checkboxes.

- [ ] Number of Checkboxes near each name changes dynamically as you change the total number of nights for the stay
- [ ] Interfacing function that feeds the checkbox input information to the Stay() class.

**Comment by rakmo97** [comment]
@K-Ramos 
- [ ] Disable original checkboxes after original calculation
- [ ] Disable original name-input boxes in modifications section
- [ ] Keep Person 1, Person 2, Person 3, etc. in the modifications section.
- [ ] Numbers over the checkboxes (Night 1 2 3, etc.)

**Comment by K-Ramos** [comment]
I think the numbering should be done in a separate issue. The current changes should be merged
